### PR TITLE
docs (html): recipe for external files in template

### PR DESCRIPTION
**Pull request by asins**
## Rollup Plugin Name: `html`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description
This method provides the ability to reference external css/js files for the generated html, and supports adjusting the file loading sequence.
Method source once issues: https://github.com/rollup/plugins/issues/755

when using it:

```js
import html from '@rollup/plugin-html';
import templateExternalFiles from '@rollup/plugin-html/recipes/external-files';
import postcss from 'rollup-plugin-postcss';

export default [{
  input: [ 'demo/demo.ts' ],
  output: [ { file: 'dist/demo.js' } ],
  plugins: [
    postcss({
      extract: 'demo.css',
      minimize: false,
      use: ['sass'],
      extensions: ['.scss', '.css'],
    }),
    html({
      title: 'sdk demo page',
      publicPath: './',
      fileName: 'demo.html',
      attributes: { html: {lang: 'zh-cn'} },
      template: templateExternalFiles([
        { type: 'js', file: 'example1.js', pos: 'before' },
        { type: 'js', file: 'example2.js', pos: 'before' },
        { type: 'js', file: 'example3.js' },
        { type: 'js', file: 'example4.js', pos: 'before' },
        { type: 'css', file: 'example1.css', pos: 'before' },
        { type: 'css', file: 'example2.css', pos: 'before' },
        { type: 'css', file: 'example3.css' },
        { type: 'css', file: 'example4.css', pos: 'before' },
      ]),
    }),
  ],
}];
```

The content of the generated html file:
```html
<!doctype html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>sdk demo page</title>
    <link href="./example1.css" rel="stylesheet">
<link href="./example2.css" rel="stylesheet">
<link href="./example4.css" rel="stylesheet">
<link href="./demo.css" rel="stylesheet">
<link href="./example3.css" rel="stylesheet">
    </head>
    <body>
      <script src="./example1.js"></script>
<script src="./example2.js"></script>
<script src="./example4.js"></script>
<script src="./demo.js"></script>
<script src="./example3.js"></script>
  </body>
</html>
```

### CODE REVIEW

**Comment by shellscape** [comment]
thanks!

**Review by shellscape — APPROVED** [review]

**Comment by cll123456** [comment]
I have a question, how to add html content ( such as : `<div id="app"></div>`)?

**Comment by cll123456** [comment]
I have a question, how to add html content ( such as : `<div id="app"></div>`)?

**Comment by cll123456** [comment]
I have a question, how to add html content ( such as : `<div id="app"></div>`)?

**Comment by asins** [comment]
> I have a question, how to add html content ( such as : `<div id="app"></div>`)?

In the settings of pollup's html plug-in, the DOM structure is hoped to be added through JS, for example, you can add `document.querySelector('body').insertAdjacentHTML('beforeend', '<div id=" at the beginning app"></div>');`

**Pull request merged**
