### PR TITLE
fix(multi-entry): downgrade matched dependency

### PR DESCRIPTION
**Pull request by lshadler**
## Rollup Plugin Name: `multi-entry`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

The `matched@^5` dependency has an [explicit requirement](https://github.com/jonschlinkert/matched/compare/4.0.0..5.0.0) for `node@12`, which conflicts with the supportability of the plugin. This PR downgrades the version to support node 10. I am happy to provide unit tests if possible, please let me know how to move forward on that front 😄

### CODE REVIEW

**Review by lukastaegert — APPROVED** [review]

**Comment by TrySound** [comment]
I published matched 5.0.1 with fixed node support

**Comment by shellscape** [comment]
@TrySound thank you! @lshadler does that resolve your issue?

**Comment by shellscape** [comment]
It looks like this is resolved by the `matched` update so I think we can close this. Thank you for raising this for attention!

**Comment by lshadler** [comment]
Yep, thank you for the downgrade! This solves my issue 👍

**Pull request closed without merging**
