### PR TITLE
chore: update estree-walker

### PR DESCRIPTION
**Pull request by larsrh**
## Rollup Plugin Name: inject, commonjs, pluginutils, strip

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers:

### Description

Update estree-walker dependency

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for opening this PR. With the nature of the monorepo as it is, we'll need to break functional PRs that touch multiple plugins into individual PRs for each plugin. Our repo here doesn't publish all plugins at once, and each is treated individually. (For metadata changes we don't have to do this)

This isn't mentioned in the contributing document and that's a shortcoming that I'll remedy.

**Comment by larsrh** [comment]
@shellscape Fair enough. Would you like me to do the splitting?

**Comment by shellscape** [comment]
If you'd like to take that on, sure. If you'd rather not I'd completely understand too. If it were me, I'd:

- revert all but one package (commonjs)
- squash the commits in this branch and rename the commit to something like: `chore(commonjs): update estree dependency`
- then one by one, do update and commit each package with a separate commit
- then ping for approval

At that point we'd do a regular merge, and we can fit all update commits into one PR.

**Comment by larsrh** [comment]
Alright, I'm on it.

**Comment by shellscape** [comment]
FWIW I'm tackling the `rollup-plugin-*` to `@rollup/plugin-*` update for the entire repo right now, and any out of date deps are getting a bump. I should have a PR up tonight.

**Comment by larsrh** [comment]
Ok, I'll hold back then.

**Comment by shellscape** [comment]
I'm going to merge your PR so you get credit for that. The plugins you've updated are going to get a bump with the work I'm doing, so we're all good.

**Pull request merged**
