### PR TITLE
fix(repo): trigger releases

### PR DESCRIPTION
**Pull request by lukastaegert**
## Rollup Plugin Name: `{name}`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description
This adds a small unimportant change to all dependencies to hopefully trigger automatic releases.

### CODE REVIEW

**Comment by shellscape** [comment]
I'm really confused what the purpose of this PR is. It looks like the rollup version is being downgraded?

**Comment by lukastaegert** [comment]
It is not really a downgrade because the latest version is still in the range. But I need to have an actual change in every single package to trigger the release script, which again will then hopefully find the commit with the actual change to release. Or so goes the theory.

**Comment by shellscape** [comment]
Can you PLEASE stop merging without approvals from the rest of the maintainers? This one is messed up too.

**Comment by shellscape** [comment]
I've cancelled the action for this PR and reset master to the previous commit. See https://github.com/rollup/plugins/pull/1326#issuecomment-1285882086

Because #1326 wasn't merged correctly, we now need to clean up the repo's commits and reapply PRs correctly. So I'd ask you to take a pause until I can get to cleaning this up this afternoon.

**Comment by lukastaegert** [comment]
Ok, if you had the release run through, then all packages would have been released with correct changeling. I will not put any more work into this, that was completely unnecessary.

**Comment by shellscape** [comment]
I'm sorry but you're mistaken. This PR would not have released any plugins. I commented in #1326 about what the commit message would need to be to make that happen.

I've also asked for collaboration with sweeping changes like this, and the self-merges are bypassing the review process in the repo, which isn't cool. No one is asking you to stop or walk away from this, just to slow down and respect the review process. A little patience would have let us catch the mistakes.

**Pull request merged**
