### PR TITLE
Fix plugin-html’s "files" array in package.json

### LINKED ISSUE #801: Missing type declarations for @rollup/plugin-html
- Rollup Plugin Name: @rollup/plugin-html
- Rollup Plugin Version: 0.2.2

### Feature Use Case
Using it from TypeScript

### Feature Proposal
You should ship the `index.d.ts` for @rollup/plugin-html

### PR DESCRIPTION
**Pull request by flying-sheep**
## Rollup Plugin Name: `html`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [ ] no
- [x] N/A

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: Fixes #801

### Description

When migrating this to typescript, you forgot to update the files array

### CODE REVIEW

**Comment by flying-sheep** [comment]
@shellscape anything keeping you from merging & releasing?

**Comment by shellscape** [comment]
have patience. we do have busy lives away from the computer.

**Comment by flying-sheep** [comment]
Haha yeah, I know how thankless being a maintainer can be, sorry for pushing.

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
