### PR TITLE
fix: Update dependency `@rollup/pluginutils` to ^5.0.1

### PR DESCRIPTION
**Pull request by meyfa**
## Rollup Plugin Name: (too many to list)

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [X] other (dependency update)

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [X] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: #1315

### Description

pluginutils version 4 has a missing production dependency on `@types/estree`, which manifested itself in issue #1315. pluginutils v5.0.1 is now released that fixes this problem (via #1320). This patch updates all plugins that depend on pluginutils to use the fixed version.

### CODE REVIEW

**Comment by lukastaegert** [comment]
cc @shellscape if it is possible to trigger a release across half the repo with a single commit, and how to format the commit messages. I do not date trigger merge on this one without your feedback, but the changes look fine to me.

**Comment by lukastaegert** [comment]
There are some build failures across the repo that need some looking into

**Review by lukastaegert — APPROVED** [review]

**Comment by lukastaegert** [comment]
Ok, so the release script did not release anything because it requires a separate commit for every package. So I guess we either need to create a separate PR for every single package, or create a PR with a separate commit for every package (with the pattern `fix(pluginname): Update dependency @rollup/pluginutils to ^5.0.1`) and then temporarily turn of squash merging in favor of a fast-forward merge.

**Comment by lukastaegert** [comment]
Ok, I reverted the commit to master and put it into a separate branch to disect later

**Comment by meyfa** [comment]
Oh, that's unfortunate. At least now we know. I have some time available right now to work on this. Would you like me to make a bunch of PRs or one PR with many commits, or do you want to deal with it some other way?

Also, it seems like the babel problem is now happening on the master branch?

**Pull request merged**
