### PR TITLE
feature(commonjs): support cache/resolve access inside dynamic modules

### PR DESCRIPTION
**Pull request by danielgindi**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

### Description

There are edge cases like the `stealthy-require` package (i.e used by `request-promise-native`) - that manipulate the cache in some ways.  
(In this specific example it makes sure that you can require a copy of the module, in order to make changes to it.)

For these cases, you can now access `require.cache` and `require.resolve` (redirected to `commonjsRequire.*`) - while in the context of a dynamically registered module.  
For normal modules - nothing is changed.

### CODE REVIEW

**Comment by danielgindi** [comment]
Anyone knows what these circleci security audit issues are? New warnings about some npm dependency?

**Comment by benmccann** [comment]
@danielgindi try rebasing against master. I included the fix for the security audit in https://github.com/rollup/plugins/pull/715

**Comment by danielgindi** [comment]
@shellscape Any plans on merging this?

**Comment by shellscape** [comment]
@danielgindi please ping the reviewers again. I'm running behind on all things OSS due to life and work right now. I should be back on track in a week or two.

**Comment by danielgindi** [comment]
@guybedford @LarsDenBakker @lukastaegert

**Review by LarsDenBakker — APPROVED** [review]

**Pull request merged**
