### PR TITLE
docs(html): clarify the template option in the docs for html plugin

### PR DESCRIPTION
**Pull request by simonxabris**
## Rollup Plugin Name: `@rollup/plugin-html`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
#630 

### Description

This PR updates the docs for `@rollup/plugin-html` clarifying the what the `template` options receives as an argument. I explained it more in the above mentioned issue. If you think the wording is not clear enough please make suggestions and I'll make the necessary changes!

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for opening a PR. This is one of those rare times that we need a test to validate the documentation change. We won't ask you to do that, but I will ask you to be patient on getting this PR merged until we've added a test to verify the structure of the parameters.

**Comment by simonxabris** [comment]
Honestly I'd be happy to contribute the tests as well if you could give me some pointers about what you would expect to see. But if it's something you want to do yourself (or someone on the rollup team) I understand that too.

**Comment by shellscape** [comment]
Cool, I just didn't want to put that burden on you. Basically what we need a test to do is snapshot the arguments for both types of array entries in the template handler. That'll be our sanity test in case the upstream API changes (in a new version of Rollup) or the function signature is changed.

**Comment by simonxabris** [comment]
Thanks, I'll try to push the changes as soon as I can.

**Comment by simonxabris** [comment]
I think this should be on hold until this is resolved: https://github.com/rollup/plugins/pull/634#discussion_r516922360

**Comment by simonxabris** [comment]
So I've did some testing and here's what I found. The `files` array that the `template` function receives will be an object, where the keys are the file extensions of the different types of assets the will be written to disk and its value is an array of assets. So for example it can have keys such as `js`, `map`, if you use some kind of plugin to import css, it will have a `css` key, if you use the `wasm` plugin it will have a `wasm` key.

I'll push a new commit that updates the docs according to what I've found.

**Comment by shellscape** [comment]
@simonxabris checking in on this one

**Comment by shellscape** [comment]
Closing as abandoned.

**Pull request closed without merging**
