### PR TITLE
docs(node-resolve): Fix mainFields valid values

### PR DESCRIPTION
**Pull request by dasa**
## Rollup Plugin Name: `node-resolve`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

The valid value for `mainFields` should be `jsnext:main` instead of `jsnext`.

### CODE REVIEW

**Comment by shellscape** [comment]
> bugfixes and features will not be merged without tests

Also, please cite your sources for asserting that this new default value is correct versus the old.

**Comment by dasa** [comment]
Example usage:

https://github.com/rollup/plugins/blob/ee5be6a7d8709e42821f6aeabbcad18a4af4dc66/packages/node-resolve/test/test.js#L18

**Comment by shellscape** [comment]
@dasa unfortunately that's not what I asked for. if you're going to claim that the current implementation is wrong, you need to cite sources to back that claim up. citing your own code is not citing a source.

**Comment by dasa** [comment]
> citing your own code is not citing a source.

That code is from this repo.

Here's a blog article: https://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/

Here's where I ran into this: https://github.com/moment/moment/blob/develop/package.json#L26

**Comment by shellscape** [comment]
Thanks for adding that info. We'll have some maintainers take a look.

**Comment by Andarist** [comment]
@shellscape actually any strings are valid, you can make the node-resolve plugin to load packages based on any, arbitrary, "main" fields in package.json manifests. However, indeed `jsnext:main` has been used in the wild (and not `"jsnext"`) in the past, for example this page mentions that: https://github.com/rollup/rollup/wiki/pkg.module

**Comment by dasa** [comment]
Perhaps the `Valid values` heading should be changed as well then to something else like `Common values`?

**Comment by shellscape** [comment]
Thanks for weighing in everyone

**Pull request merged**
