### PR TITLE
chore(commonjs)!: bump glob's version

### LINKED ISSUE #1691: [@rollup/plugin-commonjs]: vulnerability in inflight
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 25.0.7

`@rollup/plugin-commonjs` depends on inflight and it is vulnerable.
https://security.snyk.io/vuln/SNYK-JS-INFLIGHT-6095116

```
 @rollup/plugin-commonjs@25.0.7
  └─┬ glob@8.1.0
    └── inflight@1.0.6
```

### Expected Behavior

`@rollup/plugin-commonjs` package doesn't depend on `inflight` package

### Actual Behavior

`@rollup/plugin-commonjs` package depends on `inflight` package

### Additional Information

To fix the vulnerability need to update `glob` package to version 10+

### PR DESCRIPTION
**Pull request by younggglcy**
## Rollup Plugin Name: `@rollup/plugin-commonjs`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:   resolves #1691 

### Description

BREAKING CHANGES: Requires Node.js version >=16.0.0 or >= 14.17, this is the same as glob's need.

both `glob` and `shx` have `inflight` in their deps, so this PR bumps `glob` to the latest and removes `shx`, since it's not been used.

### CODE REVIEW

**Comment by akashennn** [comment]
Hi any update on this? There is a vulnerability introduced thought this

**Review by lukastaegert — CHANGES_REQUESTED** [review]
It seems this update is breaking tests that rely on glob, so we need to figure out what the breaking changes were.

**Comment by mehdibo** [comment]
Hello, any updates on this? or is there a workaround 
Facing this issue:
 > warning nuxt > nitropack > @rollup/plugin-commonjs > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.91

**Comment by younggglcy** [comment]
CI tests failed due to wrong order returned by `glob.sync()` [here](https://github.com/rollup/plugins/blob/0090e728f52828d39b071ab5c7925b9b575cd568/packages/commonjs/src/dynamic-modules.js#L44). 
That's because, since glob v9, results will not be sorted.
FYI: https://github.com/isaacs/node-glob/issues/576

**Comment by shellscape** [comment]
@younggglcy I think this is good to merge, but please rebase/merge from master again. CI isn't happy.

**Comment by younggglcy** [comment]
> @younggglcy I think this is good to merge, but please rebase/merge from master again. CI isn't happy.

fixed.

**Pull request merged**
