### PR TITLE
fix(node-resolve): preserve moduleSideEffects when re-resolving files

### LINKED ISSUE #1244: commonjs's resolver breaks moduleSideEffects treeshaking even for esm-only code
- Rollup Plugin Name: commonjs (I guess?)
- Rollup Plugin Version: 22.0.2
- Rollup Version: 2.78.0
- Operating System (or Browser): windows 11
- Node Version: 16.16.0
- Link to reproduction: https://replit.com/@simonbuchan/rollup-plugin-commonjs-treeshake#output/bundle.js

### Expected Behavior

Due to `"sideEffects": false`, the content of `evil.js` should not be included in the bundle:

```
Object.prototype.evil = "don't expect this to be here";
```

### Actual Behavior

When `commonjs()` is included in `plugins`, the side effects are included, despite there being no require / exports or other required transformations.

### Additional Information

AFAICT, this is essentially what breaks the majority of tree-shaking out there, `lodash-es`, `@aws-sdk`, etc...

This seems to be due to the injected `commonjs--resolve` plugin, replacing `commonjs()` with: `{ ...commonjs(), options: undefined }`, which prevents this injection causes the issue to go away.

Injecting logging after said injected plugins' `resolveId` shows it returning each module twice, first with `moduleSideEffects` set to true, then set to false. Not sure why the same plugin `resolveId` is being called twice, with the same options even.

The upshot seems to be that the `moduleSideEffects` value from, e.g. `@rollup/plugin-node-resolve` is getting dropped by `commonjs`.

### PR DESCRIPTION
**Pull request by lukastaegert**
## Rollup Plugin Name: `node-resolve`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
- resolves #1244
- closes rollup/rollup#4615

### Description
Breaking change: The plugin now requires at least rollup@2.76.0 to run due to its use of the new `order` plugin hook ordering feature.

This fixes a really important bug that basically rendered `moduleSideEffects` useless when used together with the commonjs plugin. The problem is that as part of its functionality, `node-resolve` "re-resolves" the id in the end by calling `this.resolve` again with a `skipSelf` flag so that the call skips the node-resolve plugin.

A feature of `skipSelf` is, that if another plugin uses `this.resolve` again in response to the call with the same source and importer, then this call is also not forwarded to `node-resolve`.

This is what the `commonjs` plugin does. Then the commonjs plugin takes the result and passes it to `this.load` to inspect the code of the module before resolving. However as the result was not processed by `node-resolve`, it does not contain the `moduleSideEffects` information. When `this.load` is called for an id, the value of `moduleSideEffects` can no longer be changed by any other `resolveId` hook and thus `moduleSideEffects` gets ignored.

#### Solution

`node-resolve` no longer uses `skipSelf`. Instead, it stores the resolve information in a custom resolve attribute and directly responds with this information when the attribute is present, thus giving `commonjs` the correct `moduleSideEffects` attribute.

This fixes the bug, but it breaks some tests that rely on the `skipSelf` attribute. This is not an issue if the `node-resolve` plugin is the last plugin. To emulate this, I added an `order: "post"` attribute to the `resolveId` hook, which is a new feature from rollup@2.76.0, hence the breaking change. It basically ensures the hook runs last, which makes a lot of sense for a "catch-all" resolver like node-resolve and might solve other issues as well.

Alternatively, I considered fixing this in Rollup core, but allowing later `resolveId` hooks to change `moduleSideEffects` breaks other things and is not a solution.

Another alternative approach could be for `node-resolve` to itself use `this.load` itself to access the mutable `moduleSideEffects` of the actual module in question. If you think this would be a better solution, then we can also go there.

This is a really important bug that should have been fixed long ago, but apparently it took some time to be noticed.

cc @simonbuchan

### CODE REVIEW

**Comment by simonbuchan** [comment]
Thanks for putting all this work in so quickly! Certainly it would have taken me a lot longer, if ever.

I'd still be interested to see if the nested resolveId behavior we discussed is intentional too (see my draft pr linked above): at the moment it seems a little off that it always defaults the last result properties: Basically at the moment adding a plugin that knows less breaks plugins that know more. I suppose it could also just forward the previous result if it's relevant in most cases.

**Comment by lukastaegert** [comment]
That is likely not possible to be fixed, at least not in the way you think. The problem is that Rollup cannot know after which resolve the module will be loaded, and what is "first" and "second" very much depends on the plugin observing it. The value of the attributes are set when the module is loaded, and it is either the attributes with which `this.load` is called, or if the module has not been loaded yet, the result of the `resolveId` chain started by Rollup itself. And changing the attributes after a call to `this.load` violates other guarantees as changes in `load` and `transform` hooks always need to be able to override changes in `resolveId`.

There would be yet another approach: If node-resolve also takes over loading a module and adds the attributes at that point in time.

**Comment by simonbuchan** [comment]
Thanks!

**Comment by simonbuchan** [comment]
Note also this should mostly resolve this troubleshooting section on the site: https://rollupjs.org/guide/en/#tree-shaking-doesnt-seem-to-be-working

**Comment by lukastaegert** [comment]
Awesome, was just waiting for a go as I am not code-owner here

**Comment by simonbuchan** [comment]
Thanks everybody: so far it's looking really nice!

I did get a weird issue with it complaining about a missing export from a commonjs module that it wasn't before, but deleting the rollup cache cleared that up, and I'm using the rollup API, so I'm probably just doing something wrong. Perhaps bumping to rollup 3 would have fixed it too...

**Comment by simoneb** [comment]
The Dependabot PR which tried to bump this package to the version including this change broke https://github.com/nearform/github-snooze-chrome-extension/pull/144. This suggests that there is a breaking change and I'm not sure what's the way to fix it.

**Comment by lukastaegert** [comment]
Seems similar to #1258, you should track that issue

**Comment by frangio** [comment]
> Breaking change: The plugin now requires at least rollup@2.78.0 to run due to its use of the new order plugin hook ordering feature.

Please include this kind of thing in the changelog! Had to find the PR to realize what was breaking.

**Comment by michaelfaith** [comment]
Working on updating from 13 to 14, and encountering this error that seems to related to this change.  Should I raise a new issue for this?
```
src/index.ts → build/cjs/index.js, build/esm/index.js...
[!] (plugin rpt2) Error: Error running plugin hook resolveId for node-resolve, expected a function hook.

    at error (D:\src\ux-foundry\.yarn\cache\rollup-npm-2.75.6-6a523c1244-df83c6d43a.zip\node_modules\rollup\dist\shared\rollup.js:198:30)
    at throwInvalidHookError (D:\src\ux-foundry\.yarn\cache\rollup-npm-2.75.6-6a523c1244-df83c6d43a.zip\node_modules\rollup\dist\shared\rollup.js:22724:12)
    at D:\src\ux-foundry\.yarn\cache\rollup-npm-2.75.6-6a523c1244-df83c6d43a.zip\node_modules\rollup\dist\shared\rollup.js:22865:24

```
We're using yarn 3 w/pnp and the following versions:
- @rollup/plugin-node-resolve: 14.1.0
- rollup: 2.74.0

**Comment by shellscape** [comment]
@michaelfaith please _do not_ cross post in multiple threads. if you feel you have a valid bug, please open a new issue and follow the requirements of the bug template.

**Comment by michaelfaith** [comment]
Understood.  I wasn't sure if that issue would still be monitored, since it was closed.  Apologies.

**Comment by michaelfaith** [comment]
I see.  The main README still shows lower version support.  So I wasn't looking deeper there. Sorry for wasting you guys' time.

**Comment by simonbuchan** [comment]
Actually, that sounds like a bug, thanks for reporting it! If noone else beats me to it I'll make a PR to fix it.

**Comment by janpe** [comment]
@lukastaegert after updating this plugin to 14 I get the following error that wasn't there before:
```
[!] (plugin commonjs--resolver) Error: Cannot find package '@babel/plugin-transform-runtime' imported from [...]/babel-virtual-resolve-base.js
```

If I install the mentioned plugin, I get the following error and I'm stuck:
```
[!] (plugin commonjs--resolver) Error: Rollup requires that your Babel configuration keeps ES6 module syntax intact. Unfortunately it looks like your configuration specifies a module transformer to replace ES6 modules with another module format. To continue you have to disable it.

Most commonly it's a CommonJS transform added by @babel/preset-env - in such case you should disable it by adding `modules: false` option to that preset (described in more detail here - https://github.com/rollup/plugins/tree/master/packages/babel#modules ).
```

Does this make sense to you? Any ideas?

**Pull request merged**
