### PR TITLE
fix(esm-shim,swc,terser): bump version of dependencies

### PR DESCRIPTION
**Pull request by tada5hi**
## Rollup Plugin Name: `{name}`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### CODE REVIEW

**Comment by tada5hi** [comment]
@shellscape can you have a look here ? 
I don't know why, but the windows test fails, thus all tests seem to pass but at the end it dumps: " ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @rollup/plugin-swc@0.1.0 ci:test: `pnpm test -- --verbose && pnpm test:ts`"

**Comment by shellscape** [comment]
Not sure. This isn't a good combo pull request anyhow. The changes to esm-shim aren't properly described by the commit message chosen, while it's accurate for the other two plugins. Please re-author a separate PR for esm-shim, and then toss one up for the terser plugin so we can address the swc CI failure in isolation. It's definitely something we want to investigate further.

**Comment by shellscape** [comment]
@tada5hi quick ping

**Comment by tada5hi** [comment]
@shellscape sorry for the late response. Yes, I will create a separate pull request for each plugin ✌️.

**Pull request closed without merging**
