### PR TITLE
chore(html): upgrade TypeScript

### PR DESCRIPTION
**Pull request by benmccann**
## Rollup Plugin Name: `html`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [X] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [X] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

Upgrade to TypeScript 4.1.2

### CODE REVIEW

**Review by NotWoods — APPROVED** [review]

**Comment by shellscape** [comment]
@benmccann bit by the pnpm bug

**Comment by shellscape** [comment]
@benmccann why closed?

**Comment by shellscape** [comment]
Tongue in cheek. It's that pnpm-lock conflict that gets us all the time.

**Comment by shellscape** [comment]
Looks like one of the other PRs resolved the conflict.

**Pull request merged**
