### PR TITLE
feat(typescript): add resolve options

### PR DESCRIPTION
**Pull request by janpe**
### Note

The commits in this PR are by @chiefidiot. They originally created PR #890 for this. I'm only opening this PR myself since the original one only lacks resolving conflicts and I wasn't able to reach the @chiefidiot to fix those and get the PR merged. I deserve no credit for the changes seen here.

This PR contains:

- [x] bugfix
- [x] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [x] yes (bugfixes and features will not be merged without tests)
- [ ] no

Breaking Changes?

- [ ] yes (breaking changes will not be merged unless absolutely necessary)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking.

List any relevant issue numbers:
#287

### Description
When targeting files outside of the current working directory of the process, the plugin fails because if filters out all files not inside `process.cwd()`. This adds the default value to look at the resolved TS config `rootDir` option while adding an additional option to control it `filterRoot` which is passed to `resolve` in the `createFilter`. This fixes (at least my issue) seeing `Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)` in a monorepo.

### CODE REVIEW

**Comment by shellscape** [comment]
Looks like a code format issue blocking the Node 12 workflow. Please run `pnpm lint` for that plugin.

**Comment by janpe** [comment]
@shellscape that is fixed now.

**Comment by janpe** [comment]
All checks passing now.

**Comment by benmccann** [comment]
It seems like there was some garbage checked in here. PR to cleanup: https://github.com/rollup/plugins/pull/1072

**Pull request merged**
