### PR TITLE
fix(commonjs): fixed access to dynamic node_modules module with subfolder (i.e 'logform/json')

### PR DESCRIPTION
**Pull request by danielgindi**
Rollup Plugin Name: `commonjs`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

### Description

In cases where there's access to a dynamically loaded module, with a slash in the middle (i.e. `require('logform/json')`), the result was empty.  
This is due to a regex that matched cases it shouldn't have.

### CODE REVIEW

**Review by shellscape — APPROVED** [review]

**Comment by danielgindi** [comment]
I've improved that regex even more, to be somewhat readable

**Comment by danielgindi** [comment]
@shellscape I don't mean to be pushy but... ;-)

**Comment by shellscape** [comment]
@danielgindi Ideally we'd like to get at least one more pair of eyes on this before merge. Could you request a review from a few other folks?

**Comment by danielgindi** [comment]
> @danielgindi Ideally we'd like to get at least one more pair of eyes on this before merge. Could you request a review from a few other folks?

Of course :-)

**Review by LarsDenBakker — APPROVED** [review]
LGTM

**Pull request merged**
