### PR TITLE
fix: restart watch program on each build

### PR DESCRIPTION
**Pull request by huozhi**
## Rollup Plugin Name: `@rollup/plugin-typescript`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: #860 

### Description

ts watch program needs to restart on each build, otherwise the emitted assets won't change, `emittedFiles` will cache the first build all the time

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. We've just updated `master`. Please update your fork from `upstream/master`.

**Comment by huozhi** [comment]
@shellscape thank you for fixing the CI issues ❤️ I've updated the PR re-targeting latest master branch

**Comment by huozhi** [comment]
hi, is there anything else I can do to make this gets merged?

**Review by shellscape — APPROVED** [review]

**Comment by shellscape** [comment]
thanks!

**Comment by huozhi** [comment]
Hi @shellscape wanna check when this change could be published into a patch release? Or a preprelease is also good! Thanks!

**Pull request merged**
