### PR TITLE
chore(pluginutils): upgrade TypeScript

### PR DESCRIPTION
**Pull request by benmccann**
## Rollup Plugin Name: `pluginutils`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [X] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [X] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### CODE REVIEW

**Review by NotWoods — APPROVED** [review]

**Comment by benmccann** [comment]
`lint` is failing on `master`, so the failure is unrelated to this PR. See https://github.com/rollup/plugins/pull/718 for more details

**Comment by benmccann** [comment]
@NotWoods I'm not quite sure the best way to fix the `lint` error here. Using `import type` as proposed in https://github.com/rollup/plugins/pull/718 still seems the most sensible to me. I filed a bug (https://github.com/alexgorbatchev/eslint-import-resolver-typescript/issues/64) and they suggested the rule should not be enabled on TypeScript files - though it seems complicated in our case because that would also turn it off for the JS files.

So three paths forward:
- Change dynamic imports to `import type`
- Turn off the rule for `.ts` and `.js` files
- `estlint-disable-line no-undef` comments on each line

Do you have a preference on the solution here?

**Comment by NotWoods** [comment]
Can we use `overrides` in the ESLint config to only turn off the rule in TypeScript files?

**Comment by benmccann** [comment]
Thanks for the suggestion. That worked and everything is passing now

**Pull request merged**
