### PR TITLE
Add `.d.mts` `.d.cts` compact

### PR DESCRIPTION
**Pull request by loynoir**
## Rollup Plugin Name: `{name}`

This PR contains:

- [x] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description
Tested fixed
https://github.com/rollup/plugins/issues/1032

### CODE REVIEW

**Comment by loynoir** [comment]
@shellscape 
No good idea how to add this to unit test, as this need new version of ts.

**Comment by shellscape** [comment]
This PR is blocked byy comment here: https://github.com/rollup/plugins/issues/1032#issuecomment-958632653

**Comment by loynoir** [comment]
@shellscape 

https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions

**Comment by shellscape** [comment]
thanks. unfortunately that's still an experimental mode. as soon as it's stable we will be happy to add that. in the meantime I would suggest using a fork until the TypeScript org makes that stable

**Comment by shellscape** [comment]
Closing citing the last comment.

**Pull request closed without merging**
