### PR TITLE
fix(node-resolve): prevent infinite findPackageJson loop

### LINKED ISSUE #1647: Infinite loop in combination with virtual module and missing package.json
- Rollup Plugin Name:  plugin-node-resolve
- Rollup Plugin Version: 15.2.3
- Rollup Version: 4.9.0
- Operating System (or Browser): macOS Ventura 13.1
- Node Version: v20.10.0
- Link to reproduction _(⚠️ read below)_:  https://github.com/dasdeo/rollup-resolve-node-bug

### Expected Behavior

Bundling should work the same regardless from where the bundler was invoked.

### Actual Behavior

If the plugin fails to find a corresponding package.json it will hang forever.

Note that this is not remedied by setting `rootDir`.

### Additional Information

I already tracked down the offending function, it is:

```js
async function findPackageJson(base, moduleDirs) {
    const { root } = path.parse(base);
    let current = base;
    while (current !== root && !isModuleDir(current, moduleDirs)) {
        const pkgJsonPath = path.join(current, 'package.json');
        if (await fileExists(pkgJsonPath)) {
            const pkgJsonString = fs.readFileSync(pkgJsonPath, 'utf-8');
            return { pkgJson: JSON.parse(pkgJsonString), pkgPath: current, pkgJsonPath };
        }
        current = path.resolve(current, '..');
    }
    return null;
}
```

Variable `current` over time:

```
findPackageJson my-virtual-module
findPackageJson /Users/dasdeo/Desktop/rollup-bug-repo
findPackageJson /Users/dasdeo/Desktop
findPackageJson /Users/dasdeo
findPackageJson /Users
findPackageJson /
findPackageJson /
findPackageJson /
...
```

### PR DESCRIPTION
**Pull request by dasdeo**
This is fixed by checking if the root directory (/) was already looped over.

## Rollup Plugin Name: `node-resolve`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

resolves #1647

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR! We'll need a test added for this before we can merge though. The test should probably recreate the situation as noted in the linked issue, and it should fail if the fix isn't present.

**Comment by dasdeo** [comment]
I would write a unit test if I knew how since this is using the file system.

Any resources on how you deal with that in this project?

**Comment by shellscape** [comment]
yeah most of our tests use file based fixtures for executing a build. I'd use those as a reference.

**Comment by dasdeo** [comment]
I just had this thought, I could be using my repository that I used to show the bug as a template for the fixture.

I _might_ be adding the test case for this bug in the next couple of days.

Just to be sure, tests are located at https://github.com/rollup/plugins/tree/master/packages/node-resolve/test/fixtures right?

**Comment by shellscape** [comment]
> Just to be sure, tests are located at https://github.com/rollup/plugins/tree/master/packages/node-resolve/test/fixtures right?

The fixtures are there. The tests are a directory level up

**Comment by shellscape** [comment]
@dasdeo will you have the chance to write a test for this change? I'd like to merge it, but we need to protect against future regressions.

**Comment by shellscape** [comment]
Closing as abandoned.

**Pull request closed without merging**
