### PR TITLE
feat(typescript): Add typechecking!

### PR DESCRIPTION
**Pull request by NotWoods**
## Rollup Plugin Name: `typescript`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
  - Since the plugin now complains about type errors, its a breaking change.
- [ ] no

List any relevant issue numbers: #71, #105, #153

### Description

Adds full typechecking support to the official Typescript plugin!
- Code frame is now included when errors are emitted
- Builds a Typescript LanguageServiceHost to work with various APIs.
- Uses Typescript's LanguageService API to compile and typecheck files.
- Changes the base tsconfig so that browser APIs aren't included by default.
- Fixes types for util/test so that functions return promises.

### CODE REVIEW

**Comment by shellscape** [comment]
@NotWoods if this looks good to you, merge it. Which semver are you thinking for this, minor or major?

**Comment by NotWoods** [comment]
I'm thinking of major just to be safe. The new feature is fairly large so it makes sense as a major change.

**Comment by lukastaegert** [comment]
Nice work!

One question (admittedly without checking your code): Will it still be possible to use the "old" style transformations via option? I definitely think that type-checking should be enabled by default, but the old way is still probably faster and may have other advantages for development (though it does not support `const enum`s of course). Mainly that you can compile "dirty" code to try something out without littering everything with `any` casts 😉

But I do not see it as a "must have"

> Which semver are you thinking for this, minor or major?

For that reason I agree that it should be major as it is breaking for people relying on this plugin compiling their broken types 😜

**Comment by NotWoods** [comment]
I plan to add the old style back in through a separate PR 🙂

**Comment by NotWoods** [comment]
Should that option be included here to make migration easier?

**Comment by lukastaegert** [comment]
Not for me, you can always hold back on upgrading if it is on the roadmap

**Pull request merged**
