### PR TITLE
Fix typescript sourcemap generated as null

### PR DESCRIPTION
**Pull request by ziofat**
## Rollup Plugin Name: `typescript`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### CODE REVIEW

**Comment by ziofat** [comment]
This fix #260

**Comment by ziofat** [comment]
Sure thing, working on it.

**Comment by ziofat** [comment]
I am not sure how the test works, always emit error:

ERROR  @rollup/plugin-typescript@4.0.0 test: `ava`
Exit status 1

**Comment by NotWoods** [comment]
Are you running `pnpm test --filter ./packages/typescript`? Perhaps some of the pretest steps aren't running.

**Comment by ziofat** [comment]
Seems something wrong for pnpm with custom registry, using official npm registry works. Sorry for the delay, working on something else these days.

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
