### PR TITLE
Modernize @rollup/plugin-terser to module

### PR DESCRIPTION
**Pull request by vdegenne**
## Rollup Plugin Name: `@rollup/plugin-terser`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### CODE REVIEW

**Comment by tada5hi** [comment]
I would like to postpone this until we migrate the whole monorepo to esm.

**Comment by shellscape** [comment]
Let's not close PRs until we've had a chance to review.

**Comment by shellscape** [comment]
@vdegenne could you please explain your reasons for this change? We export both ESM and CJS for each package, which should make usage seamless. Is there a problem that you're trying to solve with this change?

**Comment by vdegenne** [comment]
> @vdegenne could you please explain your reasons for this change? We export both ESM and CJS for each package, which should make usage seamless. Is there a problem that you're trying to solve with this change?

Sorry I think it's a misunderstanding, I was trying to use `@rollup/plugin-terser` in `rollup.config.TS` and I had an error, adding `"type": "module"` manually into the `package.json` solved the issue...  ...until I realized I was using `"module": "NodeNext"` in my ts config. I changed the value to `Node` and the error was gone.
I see this package is still providing CommonJS so I guess you are not going to accept this change any time soon.

**Comment by shellscape** [comment]
OK thanks for explaining. Yeah unfortunately we won't be moving to only ES exports soon.

**Comment by nikelborm** [comment]
Sorry, but why is this comment marked as abuse? Is it by mistake, or is there something to be learned in communication?
image

**Comment by shellscape** [comment]
probably a fat finger

**Pull request closed without merging**
