### PR TITLE
fix(node-resolve): resolve hash in path

### PR DESCRIPTION
**Pull request by chengcyber**
## Rollup Plugin Name: @rollup/plugin-node-resolve

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

This PR is fixing https://github.com/rollup/plugins/issues/587

```
import test from 'test#foo'
```

treats as hash usage

```
import test from 'test/#/foo'
```

treats `hash` as part of package path

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
This creates a bit of a special case, for instance it would not fix it for `test/#foo/bar` but I think at least it solves the immediate problem people are having with this. So 👍  from me

**Comment by lukastaegert** [comment]
I agree this is definitely an improvement and could be released as a partial bug fix.

But looking for a long term fix, why are we stripping BOTH `#` and `?`? Because the core of the problem is that while `?` is not a valid character in file names anyway and treating it as a suffix should be safe, `#` is not. So why are we not fixing it by removing the special handling of `#` ?

I think it would still solve the original issue #486 in so far as it leaves a way to pass on information, just not via hashes. Thoughts @LarsDenBakker?

**Comment by LarsDenBakker** [comment]
I agree, ? Is the primary use case so we could leave out hashes.

**Comment by lukastaegert** [comment]
@chengcyber Would you be willing to modify this PR to remove the special handling for hashes altogether? Of course this would make this a breaking change, but I think this should be worth it in the long run.

**Comment by chengcyber** [comment]
@lukastaegert, I remove the special handling for hashes in the latest commit, please kindly take another look.

**Review by lukastaegert — APPROVED** [review]
Thanks, can be merged

**Pull request merged**
