### PR TITLE
fix(commonjs): Exclude multi-line template strings from indent

### LINKED ISSUE #1228: [commonjs] strictRequires indent with \t modifies multi-line string values.
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: 22.0.1
- Rollup Version: 2.77.2
- Operating System (or Browser):
- Node Version: v16.16.0
- Link to reproduction: https://replit.com/@simonbuchan/rollup-plugin-repro#output/bundle.js

### Expected Behavior
Multiline-string values should be preserved.

### Actual Behavior
Indent `\t` characters are blindly inserted into the multi-line string.

### Additional Information
This particular issue seems to be due to:

https://github.com/rollup/plugins/blob/add3a350e99505e15790b4915c33b1fcc5bf00ec/packages/commonjs/src/transform-commonjs.js#L534

but there are other uses of `magicString.indent("\t")` in the code-base, e.g.:

https://github.com/rollup/plugins/blob/add3a350e99505e15790b4915c33b1fcc5bf00ec/packages/commonjs/src/generate-exports.js#L12-L16

The simple fix is just don't indent code - I doubt it would be simple to implement a correct source-map-preserving indent. Perhaps instead doing a transform from multi-line template strings to single-line escape codes would also work?

### PR DESCRIPTION
**Pull request by simonbuchan**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

Fixes #1228

This excludes template literal elements (the string-ey bits) that include newlines from the two cases of `MagicString.indent()` used in commonjs.

E.g.:

```js
export default `
foo
bar
`
```

in some cases could be transformed to:

```js
export default `
\tfoo
\tbar
\t`
```

### CODE REVIEW

**Comment by simonbuchan** [comment]
Note, one thing to look into is if it's actually OK to include gathering the `TemplateElement` ranges in the same `walk` as everything else - it does skip some branches, but it seemed to be safe from what I could see.

**Comment by simonbuchan** [comment]
As a comment, the current husky seems broken with a recent pnpm - it tries to run using `pnpx --no-install`, which doesn't work. Is this known? I had to edit my `.git/hooks/husky.sh`.

**Review by shellscape — APPROVED** [review]
Looks good to me, nice work. We like to wait until one more maintainer approves before merge.

**Review by lukastaegert — APPROVED** [review]
Great work and thanks a lot for taking up on this so quickly, these kind of contributions really move the project forward!

> Note, one thing to look into is if it's actually OK to include gathering the TemplateElement ranges in the same walk as everything else - it does skip some branches, but it seemed to be safe from what I could see

I agree, at least I saw no obvious omissions. These walks are rather expensive, so using the existing walk is a good thing. If we find we missed something, I would think we should rather replace the skipping logic with an adapted logic that just skips most of the switch statement except the `TemplateElement` logic.

I think this is good to be merged.

**Comment by simonbuchan** [comment]
Thanks! Feels good to get a fix into such a cool project!

**Pull request merged**
