### PR TITLE
build(babel): define babel as dep instead peer-dep

### PR DESCRIPTION
**Pull request by tada5hi**
## Rollup Plugin Name: `babel`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### CODE REVIEW

**Comment by Andarist** [comment]
Could you mention **why** you want to make this change? I don't want to be dismissive so I would like to hear out the argument behind this. However, from my PoV, this is likely to be rejected.

**Comment by tada5hi** [comment]
This is for consistency. This is mentioned in the swc pull request, which you are also involved in. There is no reason why Babel should be a peer dependency here and thus be an exception. Both Babel and swc are for transpilation.

**Comment by shellscape** [comment]
@Andarist a few of the maintainers hashed out the same discussion on the new swc plugin PR here: https://github.com/rollup/plugins/pull/1412#discussion_r1085647334

Conclusion was that since `createConfig` is marking those dependencies as external, there's no default reason that a dependency like `@swc/core` (or babel) shouldn't be a direct dependency. Now, that doesn't mean that there isn't a non-obvious reason. This PR was opened to get all of the plugins on the same page, as we have other exceptions like the typescript plugin and the typescript peerDep, but if there's a reason for plugin-babel to keep the peerDep, I'm all ears.

**Comment by Andarist** [comment]
This puts the "host project" at risk of installing different versions of Babel/SWC/etc and at risk of using those different versions by various tools. It's no fun to debug why a thing transpiles OK when running tests with Jest but it doesn't transpile OK when bundling (just an example).

This could also lead to weird issues when a plugin/preset/whatever created in the host project could not be recognized as such by another instance of Babel that got loaded by `@rollup/plugin-babel`. This depends on what kind of checks a tool like Babel do internally but this could easily introduce a breakage of this type. Consider this situation:
```js
// .babelrc.js
module.exports = { plugins: require('./local-plugin.js') }

// local-plugin.js
const babel = require('@babel/core')
module.exports = babel.createPlugin(/* ... */)
```

This doesn't reflect the actual Babel plugin API etc. I'm only using it to illustrate how the project could use a different version of Babel than we'd do internally and how that could lead to problems.

In the case of Babel (and other tools like this) I think that the peer dep is a better choice and that the user has to "provide" that is better.

**Comment by shellscape** [comment]
@benmccann the reply above is a pretty well-reasoned rebuttal of the prior discussion for the swc plugin. thoughts?

**Comment by benmccann** [comment]
babel and swc feel different to me because Babel is used by tons of dependencies like Jest, etc. That means you're more likely to run into conflicts, already have other dependencies specifying it as a peerDependency, etc. I'm not sure that users are likely to have anything else in their projects depending on swc?

**Comment by Andarist** [comment]
A test runner (like Jest) often depends on some kind of a transformer - and ideally, one that uses the same tool under the hood that is used for bundling. For example, I have one project depending on `@swc/jest` - and that defines `@swc/core` as its peer dep.

IMHO the popularity of the project shouldn't impact the outcome of this decision. To me, it all boils down to the nature of a given project. I think that we can all say that Babel and SWC have the same nature here and it makes sense to me to treat both equally.

**Comment by benmccann** [comment]
That's fair. I wasn't aware `@swc/jest` existed. I suppose in that case making it a `peerDependency` is pretty reasonable

**Comment by tada5hi** [comment]
> babel and swc feel different to me because Babel is used by tons of dependencies like Jest, etc. That means you're more likely to run into conflicts, already have other dependencies specifying it as a peerDependency, etc. I'm not sure that users are likely to have anything else in their projects depending on swc?

This is also the case with swc. In addition, swc offers an alternative to ts-jest, with the name ts-jest.

**Comment by Andarist** [comment]
I think the consensus has been reached here that those should stay as peer deps, so im going to close this for housekeeping purposes. However, if somebody is still in doubt - let’s continue discussing this.

**Comment by tada5hi** [comment]
So @shellscape what is your decision ? I agree with @Andarist  that Babel as well as swc should be managed as peer dependency, for which I also argued from the beginning in a discussion with approx. 30 messages under different aspects.

**Comment by shellscape** [comment]
There's no need to quantify your participation in a discussion. That comes across a little salty. We have these kinds of discussions because they can evolve and our maintainers each bring unique perspective. It's the utmost collaborative spirit. @Andarist brought new perspective and info that was compelling and added to the context of the conversation.

I agree we've reached a new consensus; peer dependencies is appropriate. 

I'll canonize this in the contributing docs in the next few days. Really appreciate everyone jumping into this one.

**Pull request closed without merging**
