### PR TITLE
chore(repo): enable `consistent-type-imports` for typescript files

### PR DESCRIPTION
**Pull request by jerry-lllman**
## Rollup Plugin Name: `{name}`

This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

we added eslint rule `'@typescript-eslint/consistent-type-imports': 'error'` 
It can make some optimizations.
For example, if you `import typescript`, the whole typescript library will be imported, but the `import type typescript` this library will not be imported, saving a lot of volume. 

`typescript` documentation is described as follows
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export

### CODE REVIEW

**Review by lukastaegert — COMMENTED** [review]
Thank you. IMO though, doing this manually is an unmaintainable chore. If we want this, we should throw

```
'@typescript-eslint/consistent-type-imports': 'error'
```

into the ESLint config. This rule has an auto-fixer.

**Comment by jerry-lllman** [comment]
> 

ok, i add it, and changed the code that does not conform to this rule.

btw, my first commit is not manually, it's fixed by this rule~

**Comment by lukastaegert** [comment]
> btw, my first commit is not manually, it's fixed by this rule~

😅 Makes sense

**Comment by shellscape** [comment]
@jerry-lllman Please fill in the Description of the pull request template. I'm familiar with the rule and it's intent and purpose, but why do we need to enforce this? Please make your case in the Description.

**Comment by jerry-lllman** [comment]
> @jerry-lllman Please fill in the Description of the pull request template. I'm familiar with the rule and it's intent and purpose, but why do we need to enforce this? Please make your case in the Description.

@shellscape I have added the description🥳

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
