### PR TITLE
fix(typescript): add missing imports

### PR DESCRIPTION
**Pull request by apfelbox**
## Rollup Plugin Name: TypeScript

**This PR contains:**

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

**Are tests included?**

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

**Breaking Changes?**

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

I have no idea how to test this, as we would need to run the build with both versions of TypeScript and I don't know if sth like this is already set up for this repository).

**List any relevant issue numbers:**
* Fixes part of https://github.com/rollup/plugins/issues/626

### Description

These two imports were missing and fail the TypeScript build of the Typescript rollup plugin with TypeScript 4.0+
Not sure if they failed for ^3.9 as well.

I tested this change with both TypeScript 3.9.7 and 4.0.5 and it works.
Doesn't seem to fix the last issue of https://github.com/rollup/plugins/issues/626 though.

### CODE REVIEW

**Comment by apfelbox** [comment]
The second issue is here:

```typescript

type ElementType<T extends Array<any>> = T extends (infer U)[] ? U : never;
                           ^^^^^^^^^^

type StagedTransformerFactory<T extends TransformerStage> = ElementType<CustomTransformers[T]>;
                                                                        ^^^^^^^^^^^^^^^^^^^^^
```

Because as every property of `CustomTransformers` can be undefined, `CustomTransformers[T]` is the `defined type|undefined`.

And therefore the type tries to assign `undefined` to `T extends any[]`, which doesn't work.

There are two possible fixes, but I am (semantically) not sure, which one is the better fit.

### Solution 1: allow undefined in `ElementType`

```diff
- type ElementType<T extends Array<any>> = T extends (infer U)[] ? U : never;
+ type ElementType<T extends (Array<any>|undefined)> = T extends (infer U)[] ? U : never;
```

### Solution 2: making all properties required, before fetching them

```diff
- type StagedTransformerFactory<T extends TransformerStage> = ElementType<CustomTransformers[T]>;
+ type StagedTransformerFactory<T extends TransformerStage> = ElementType<Required<CustomTransformers>[T]>;
```

**Review by NotWoods — APPROVED** [review]

**Comment by apfelbox** [comment]
If somebody can give me feedback on the question in https://github.com/rollup/plugins/pull/633#issuecomment-721250077, I can add it (and we can get this merged)

**Comment by shellscape** [comment]
@apfelbox I'm probably not as learned as you with TS, but could using `ElementType<Partial<CustomTransformers[T]>>` work here?

**Comment by apfelbox** [comment]
@shellscape I don't think that that would work. `Partial` makes every property in an interface optional (e.g. `{test: string}` -> `{test?: string}`), but they already are all optional (they all already have a `?:`).

That is the main problem, actually: as they are optional, the type of the index access in `CustomTransformers[T]` can be `undefined`, which is then in turn not accepted in the definition of `ElementType` itself.

**Comment by shellscape** [comment]
@apfelbox does #647 resolve the issue on your end? Seems to be a possible duplication of effort.

**Comment by apfelbox** [comment]
@shellscape yes, I the meantime #647 popped up and seems to be fixing the same issues.
However I would argue (and have in an comment over there) that one of the fixes is wrong.

**Comment by fernandopasik** [comment]
Is this PR the one that fixes this? https://github.com/rollup/plugins/pull/647

**Pull request merged**
