### PR TITLE
feat: support mp3

### PR DESCRIPTION
**Pull request by Zaynex**
## Rollup Plugin Name: `url`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

Support mp3 file assets.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for taking the time to create a PR. 

This is one of those features that should really be discussed before implementation. In this case, your feature is already supported via the `include` option for the URL plugin.

**Comment by Zaynex** [comment]
I realize I ignore this.Thanks. 
So,  Could 'mp3' become the default includes?

**Comment by shellscape** [comment]
We can let the other maintainers comment, but my opinion is that it's not something that would be used often so there isn't a benefit to most users in having `mp3` as a default include.

**Comment by lukastaegert** [comment]
I think it is a question of philosophy. Either we say that this plugin by default only imports the most basic assets without additional config, or it handles all common asset formats you find on the web to make it a little more "zero config". But if we go for that, then there is IMO a much longer list that should be added, like video formats, other audio formats, etc.

So to sum it up, adding this alone feels unbalanced to me.

And if we go the zero-config route, then lists of what browsers DO support can be found here: https://developer.mozilla.org/en-US/docs/Web/Media/Formats

However this is based on MIME types. As we need to go for file extensions instead, maybe something like the default file-extension to mime-type mapping for Nginx servers could be an inspiration: https://github.com/nginx/nginx/blob/master/conf/mime.types

**Comment by shellscape** [comment]
@lukastaegert this could work https://www.npmjs.com/package/ext-list

**Comment by Zaynex** [comment]
Interesting.I never thought there was so much to learn here.

**Comment by lukastaegert** [comment]
@shellscape True, but someone would still need to reduce that list to actual asset types. Would be a problem if this plugin started handling `.js` files...

**Comment by Zaynex** [comment]
If there are other people with similar needs, then we continue.

**Pull request closed without merging**
