### PR TITLE
fix: Update Rollup dependencies

### PR DESCRIPTION
**Pull request by meyfa**
## Rollup Plugin Name: all of them

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [X] other (dependency update)

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [X] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: See PR #1321 where this was discussed.

### Description

PR #1321 was reverted since the release script needs separate commits for each package.
This PR is an attempt at making that happen. I have opened it as draft, since I am on Windows and cannot test locally, so I will have to make one commit at a time and see that CI passes.

Note that the PR may not be squashed, and must instead be merged using fast-forward merge!

### CODE REVIEW

**Comment by meyfa** [comment]
Progress tracker:

- [X] alias
- [X] auto-install
- [X] babel
- [X] beep
- [X] buble
- [ ] commonjs
- [ ] data-uri
- [ ] dsv
- [ ] dynamic-import-vars
- [ ] eslint
- [ ] graphql
- [ ] html
- [ ] image
- [ ] inject
- [ ] json
- [ ] legacy
- [ ] multi-entry
- [ ] node-resolve
- [ ] pluginutils
- [ ] replace
- [ ] run
- [ ] strip
- [ ] sucrase
- [ ] typescript
- [ ] url
- [ ] virtual
- [ ] wasm
- [ ] yaml

**Comment by meyfa** [comment]
@lukastaegert All done. As you can see, each commit is individually green. This was an enormous pain to achieve, but should enable a clean fast-forward onto the master branch. I just hope the release script works this time.

**Comment by lukastaegert** [comment]
> This was an enormous pain

I know, I did this a short time ago.

> each commit is individually green

actually, I think it would have been ok for CI if only the very last commit had been green, that is the only one that is actually being tested during release. But of course this way it is even nicer. Will give it another go, fingers crossed. Thank you so much!

**Review by lukastaegert — APPROVED** [review]

**Comment by lukastaegert** [comment]
See #1327

**Comment by shellscape** [comment]
@lukastaegert I'd _really, really_ appreciate if you'd slow down a bit within the plugins repo. If it's super important, you know how to get ahold of me outside of github. All that said, this was not merged correctly for a multi-plugin commit that runs the release and publish for each plugin. All PRs should be squash merged. The PR title (and commit message) should be in the format:

```
fix(plugin1,plugin2,plugin3): some thing
```

Before merging, each PR should get _at least_ two approvals within a reasonable amount of time. That applies to maintainers as well. With the recent flurry of activity around Rollup v3, I'd previously asked for more collaboration before forging ahead. I'd like to ask for that again.

**Comment by shellscape** [comment]
I've completed the rebasing work and all plugins have been published. Thanks for your work on this, it's appreciated.

**Comment by meyfa** [comment]
You're welcome, and thank you for creating the releases!

**Pull request merged**
