### PR TITLE
chore: Adding prettier scripts and files

### PR DESCRIPTION
**Pull request by wuweiweiwu**
- Rollup Plugin Name:  NA

This PR contains:
- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [x] other (infra)

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [x] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [x] no

List any relevant issue numbers:

### Description

- since this repo already uses prettier presets for eslint it makes sense to prettier be the single source of truth for formatting. I'm a big fan of having only 1 code formatter in a project -> consistency.
- adding prettier and ci:prettier tasks in ci
- use prettier to format all `md,js,ts` except for `CHANGELOGS` since they are autogenerated

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for your work on this, but it should have been discussed ahead of time. Prettier won't be our source of truth, but rather an auxiliary. I'm sorry to have to pass on this given the amount of work I'm sure went into it. Formatting is tricky as everyone wants to add their say and their preferences. We setup the repo with the formatting that we'd be using out of the date to try and avoid debates and discussions around formatting. 

Thanks again for your work on this.

**Comment by wuweiweiwu** [comment]
@shellscape sounds good! What are the best place to have discussions about this sort of stuff? Is there a discord?

**Comment by shellscape** [comment]
You can open an issue with the blank issue template, as that really doesn't fit any of the pre-defined issue templates. There's a link at the bottom of https://github.com/rollup/plugins/issues/new/choose that says _Open a blank issue_.

FWIW I'm currently working on the `rollup-pluginutil` migration to this repo which includes wiring up `@typescript-eslint` to ESLint, which is another reason we've planned for that to be the "source of truth" for linting and formatting as it were.

**Comment by wuweiweiwu** [comment]
Sounds good! Will do next time. Thanks!

**Pull request closed without merging**
