### PR TITLE
Move dependencies to devDependencies and upgrade devDependencies

### PR DESCRIPTION
**Pull request by benmccann**
## Rollup Plugin Name: common development setup

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [X] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [X] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

List any relevant issue numbers:

### Description

The dependencies listed under `dependencies` are only used in scripts and not in any of the plugins themselves, so I believe they should be listed under `devDependencies` since they're not included in the source, but only used during the development process. I also upgraded most of the dependencies as well. They're just used during tests, etc. so won't affect the plugins themselves

### CODE REVIEW

**Comment by shellscape** [comment]
But why? The range changes are superficial, and because it's a monorepo deps vs devDeps doesn't really mean anything. If anything, maybe we talk about what it means in an issue.

I appreciate all of the work you're taking on here, but let's chat about some things before you dive right on into it. We're a team here, and the onslaught (in a goodish way) today is bananas. We're not likely to be able to approve and merge them all in a day (a week?) and because we're a team you've unloaded a lot of burden at once. A steady pace would be more welcome.

**Comment by benmccann** [comment]
It's inconsistent to have some as `dependencies` and some as `devDependencies`, so this brings greater consistency.

There are also several packages with major version bumps.

The majority of the PRs are simply bumping the TypeScript version. I'm not quite sure what is required to review those. I did mention in https://github.com/rollup/plugins/issues/679 that it would create quite a few PRs, but that was the suggestion that was made to me.

**Comment by shellscape** [comment]
I'd recommend going back and rereading what I wrote again, and absorb the message in that reply.

**Comment by benmccann** [comment]
Ok, I thought your earlier suggestion regarding repo-level changes was only referring to changes which would affect the plugin distributions. These changes are only for development tools and don't actually affect the code that end users receive from the individual plugins, so I didn't think the earlier statement applied here

I agree we should try to fix the CI issue if possible. It seems like that would address a lot of the manual review work, etc.

**Pull request closed without merging**
