### PR TITLE
fix(inject): isReference check bug

### PR DESCRIPTION
**Pull request by linsk1998**
## Rollup Plugin Name: `inject`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

disregard the bar in import { bar as foo }

For example

If my config inject "bar", the following code

```javascript
import { bar as foo } from 'bar2'
console.log(bar);
```

will transfrom to the following code

```javascript
import bar from 'bar';
import { bar as foo } from 'bar2';
console.log(bar);
```

.

But expect will not inject.

### CODE REVIEW

**Comment by shellscape** [comment]
Please provide a _**detailed**_ description of why this change is necessary, and any relevant issue numbers. (If there isn't an issue associated with this PR, you'll have to provide a good amount of information about the problem you were trying to solve.)

**Review by shellscape — APPROVED** [review]

**Review by pnevares — APPROVED** [review]

**Comment by danielgindi** [comment]
Is there ANY description of what this is about?

**Review by btd — APPROVED** [review]

**Comment by linsk1998** [comment]
@danielgindi @shellscape   I add more description.

**Comment by danielgindi** [comment]
> @danielgindi how's that update to the PR description look for you?

Not the best, but getting there. If I understand correctly, there's a situation where an import is not flagged correctly and it causes duplicate imports in the output, resulting in a syntax error.
Am I right?

**Comment by shellscape** [comment]
@danielgindi I believe that's correct. Going to move this one forward.

**Pull request merged**
