### PR TITLE
Add recommendation for tsconfig.json with TypeScript 5+

### PR DESCRIPTION
**Pull request by berniegp**
## Rollup Plugin Name: `@rollup/plugin-typescript`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description
- Added recommendations for `tsconfig.json` and TypeScript 5.0 based on the TypeScript docs and my experience here: https://github.com/berniegp/mock-xmlhttprequest/commit/ce29b1bd57b8fe710999b49f6c2f850130305aa4)
- Expanded the "Why?" presentation section
- Fixed a few typos in "TypeScript"

As far as I can see, the new `bundler` option is perfect for use with Rollup, but it would be great for someone else to have a look. It took me a long time to figure out the correct options to use with Node 16 and TS 5+ so I hope that this recommendation will help others.

Also I'm not sure if there should be extra tests to test this configuration.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. While I think this is good info, it doesn't look suited to the readme for the typescript plugin. If you're up for it, I would suggest creating a `packages/typescript/recipes/file-extensions.md` file that contained a more verbose description of the setup.

**Comment by berniegp** [comment]
I can have a look at that time permitting. You're referring to the "tsconfig.json recommendations" section to move to another page right?

Should I modify my branch to remove that part so the other changes can be merged?

**Comment by shellscape** [comment]
Yes that's correct. Since the bulk of the other changes are a change of `Typescript` -> `TypeScript`, I'd recommend just making all changes before we merge anything.

**Comment by shellscape** [comment]
Closing as abandoned.

**Pull request closed without merging**
