### PR TITLE
refactor(html): remove eslint disable

### PR DESCRIPTION
**Pull request by yagebu**
## Rollup Plugin Name: `{html}`

This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: #339 

### Description

Extracted fixes from #339:

[...] a minor refactor to get rid of an eslint-disable and fix up some minor mistakes in the README.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR

I don't think the README changes are an improvement, and contain a mistake if their own. And I'm not a fan of style change refactors without benefit. This one is a :-1: for me but we'll leave this open for a while to let other maintainers comment.

**Comment by yagebu** [comment]
> I don't think the README changes are an improvement, and contain a mistake if their own.

Could you point out the mistake? Some of the changes are really fixes though...

**Comment by shellscape** [comment]
> Specifies the name of the HTML to emit.

I believe you left out "file" in that sentence.

This is overall a subjective style change. What you're perceiving as mistakes are just another way to say the same thing. In the future I'd recommend opening a documentation issue and discussing there first.

**Comment by yagebu** [comment]
> I believe you left out "file" in that sentence.

I copied the existing line...

image

That last line being in the wrong place doesn't seem to be a subjective style change to me.

**Comment by yagebu** [comment]
> The documentation changes seem unneeded.

I had assumed they would be obvious as just fixes (with minimal style changes), but that assumption was apparently incorrect so I'll elaborate:

- The first commit moves an incorrectly placed line (Specfies the name[...]) so that it's placed with the actual option it describes.
- The `file` property of the object passed to the template function is currently described as `An Array of [...]`, however it's an Object. I'm not perfectly happy with the new wording either, so if you have any better suggestions, please change it to something better. But I find it odd to call an Object an "Array" and dismiss a fix to change that as a "subjective style change".
- The last change shows the literal output of the `makeHtmlAttributes` function. That output starts with a space, so that should be reflected in the displayed output in the README.

**Comment by shellscape** [comment]
> I had assumed they would be obvious as just fixes (with minimal style changes), but that assumption was apparently incorrect so I'll elaborate

I _really_ don't appreciate the tone of the language chosen here. This can remain open and discussed by users and other maintainers but this isn't a PR that I'm going to approve, and will be stepping away from it.

**Comment by yagebu** [comment]
> I really don't appreciate the tone of the language chosen here.

@shellscape: I'm sorry about my wording, it was not my intention to offend. I was trying to express that I was wrong to not provide more detailed descriptions of the changes in this PR.

**Comment by yagebu** [comment]
These changes are overall of minor value, so I'll close this PR. Sorry to have caused such a fuss.

Thanks for your comments and the maintenance of these plugins!

**Pull request closed without merging**
