### PR TITLE
feat(yaml): add JSON plugin features and JSON support

### PR DESCRIPTION
**Pull request by Luke-zhang-04**
## Rollup Plugin Name: `yaml`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

- feat(yaml): add preferConst, compact, namedExports, and indent options
- refactor(yaml): use dataToEsm
- feat(yaml): allow parsing of .json files
  - Since all valid JSON is also valid YAML, this plugin should also check for JSON

### CODE REVIEW

**Comment by shellscape** [comment]
Is there discussion around this that I'm missing?

**Comment by Luke-zhang-04** [comment]
No, I just wanted to be able to use it this way

**Comment by shellscape** [comment]
Well we've already got a JSON plugin to handle JSON things. Without a compelling use case I don't see the need or cause to merge this.

**Comment by Luke-zhang-04** [comment]
Ok that's fine, I just thought it would be good to have one plugin that could handle both with minimal changes

**Comment by Luke-zhang-04** [comment]
Ok if there are no plans to merge this I'll close it

**Pull request closed without merging**
