### PR TITLE
refactor(pluginutils): improve readability of attachScopes test

### PR DESCRIPTION
**Pull request by eight04**
## Rollup Plugin Name: `pluginutils`

This PR contains:

- [ ] bugfix
- [ ] feature
- [x] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: #547

### Description

Generate AST with acorn as #547 suggested. This helps us include more complex tests in the future.

### CODE REVIEW

**Comment by eight04** [comment]
It seems that the build error on Windows relates to #550

**Comment by lukastaegert** [comment]
Are the build issues fixed now? Would you update the branch with latest master?

**Comment by eight04** [comment]
How do I resolve `pnpm-lock.yaml` conflict? Is there a command for that?

**Comment by lukastaegert** [comment]
I usually just use the version from the server and then run `pnpm install` again.

**Comment by eight04** [comment]
Done

**Review by lukastaegert — APPROVED** [review]
Nice!

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
