### PR TITLE
fix(beep): ensure types are exported in npm pkg

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
## Rollup Plugin Name: `beep`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [x] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

### Description

The typings were not exported for `beep` plugin even though they existed in the package.

### CODE REVIEW

**Review by NotWoods — APPROVED** [review]

**Comment by vinayakkulkarni** [comment]
@shellscape: can you please merge this ? Thanks.

**Comment by shellscape** [comment]
@vinayakkulkarni this package isn't a priority, as it's mostly for demonstration purposes. The source is incredibly small. I don't know what your motivations are for needing this merged, but it'll be a while.

**Comment by vinayakkulkarni** [comment]
> @vinayakkulkarni this package isn't a priority, as it's mostly for demonstration purposes. The source is incredibly small. I don't know what your motivations are for needing this merged, but it'll be a while.

TypeScript throws an error when I include this package in `rollup.config.ts` file. If you merge this, TS will stop throwing errors of `d.ts` file not found.

**Comment by shellscape** [comment]
Take a moment to learn about `@ts-ignore` and the other directives, and how to leverage declaration files. Or copy the three lines that make up this plugin directly into your config.

**Comment by vinayakkulkarni** [comment]
> Take a moment to learn about `@ts-ignore` and the other directives, and how to leverage declaration files. Or copy the three lines that make up this plugin directly into your config.

I am already using a [shims](https://github.com/vinayakkulkarni/v-clappr/blob/main/shims/%40rollup/plugin-beep.d.ts) file instead of suppressing typescript errors by `@ts-ignore` or `@ts-nocheck`, since I use [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint), ESLint throws an error about not using [`@ts-<directive>`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-comment.md).

**Comment by panoply** [comment]
I like you Andrew but sometimes you sometimes you can be a tad insufferable.

**Comment by shellscape** [comment]
@panoply your reply is in violation our code of conduct https://github.com/rollup/plugins/blob/master/.github/CODE_OF_CONDUCT.md

Please consider this a formal warning. Another violation may result in limiting your ability to interact with the organization.

**Pull request merged**
