### PR TITLE
fix(replace)!: do not escape delimiters

### LINKED ISSUE #904: replace plugin. "delimiters" config is broken by "escape" internal mutation
- Rollup Plugin Name: `@rollup/plugin-replace`
- Rollup Plugin Version: `2.4.2` (currently latest)
- Rollup Version: `2.50.6`
- Operating System (or Browser): `macos` (but it's irrelevant in this case) 
- Node Version: `16` (but it's irrelevant in this case)
- Link to reproduction: https://stackblitz.com/edit/rollup-plugin-replace-broken-delimiters-option

### Expected Behavior

The `delimiters option` that is matching the `default value` should work the same

### Actual Behavior

Unfortunately, the `escape` internal function that is supposed to escape RegExp string malfunctions.
So it's impossible to reproduce the current default behavior because of that.
- it's also preventing to configure as this PR suggests https://github.com/rollup/plugins/pull/903

### PR DESCRIPTION
**Pull request by guansss**
## Rollup Plugin Name: `replace`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [x] yes (_breaking changes will not be merged unless absolutely necessary_)
- [ ] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers: #904 

### Description

Fixes #904, now delimiters given by users are no longer escaped, so it's possible to pass `['\\b', '\\b']` to revert to the default behaviour prior to #903.

It's breaking because users may have been relying on current behaviour (bug) to match special characters which are now required to be escaped.

### CODE REVIEW

**Review by danielgindi — APPROVED** [review]

**Comment by shellscape** [comment]
@guansss apologies for the delay in getting to your PR. it looks like there are a few conflicts to clean up since you submitted it. Please clean those up and we'll give this another look.

@guybedford could you lend your eyeballs to this breaking change?

**Comment by guansss** [comment]
Okay, I've rebased it onto master.

**Review by guybedford — APPROVED** [review]
Great work. Looks solid to me. Is the `escape` function still used elsewhere or can it be removed?

This is a major change so we should bump the semver version.

**Comment by guybedford** [comment]
Another thing that could be useful is accepting an actual regex for delimiters by value as well eg via `if (delimiter instanceof RegEx)` kind of thing.

**Comment by guansss** [comment]
Thanks @guybedford. Yeah, the `escape` function is still used on replacement keys.

The delimiters will end up being concatenated into a string to build the regex, so there may be no need to accept a regex.

**Comment by guybedford** [comment]
@guansss accepting a regex may still solve the original use case of supporting an unescaped input though!

**Comment by guansss** [comment]
@guybedford that makes sense, but IMO it's more like a trick and could be easily done from user-side via something like `delimiters: [/\b/.source, /\b/.source]`.

**Comment by guybedford** [comment]
@guansss at the end of the day manual regex escaping is work, and something that can be a cause of errors. Making things easier where possible without sacrificing maintainability is the goal in open source!

**Comment by guansss** [comment]
@guybedford agreed, I'm not quite into it though!😄

**Pull request merged**
