### PR TITLE
add .nodeResolve change to the readme

### PR DESCRIPTION
**Pull request by heavyk**
just ran into what's described in #412

this updates the readme to reflect the latest version of the module

## Rollup Plugin Name: `{name}`

This PR contains:

- [ ] bugfix
- [ ] feature
- [ ] refactor
- [x] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### CODE REVIEW

**Comment by vladshcherbin** [comment]
Why?

Default export works fine in `.js` configs, it's an issue with using `.mjs` configs which should be solved so that default exports work there too.

**Comment by heavyk** [comment]
right, I'm using require. all the other plugins export the function, cept this one which I have to get `.nodeResolve` or `.default` eg.

```js
const plugin_json = require('@rollup/plugin-json') // works
const plugin_inject = require('@rollup/plugin-inject') // works
const plugin_node_resolve = require('@rollup/plugin-node-resolve').nodeResolve // this one needs .nodeResolve
const plugin_commonjs = require('@rollup/plugin-commonjs') // works
```

**Comment by vladshcherbin** [comment]
I believe the real issue here is that it works differently and should be solved by updating its code to work like the other ones and not by updating readme, but I might be wrong 😉

**Comment by vladshcherbin** [comment]
@heavyk can you check node-resolve v8.1.0?

I believe it should work fine now and there is no need to change readme.

**Comment by XhmikosR** [comment]
The issue is still not fixed. `const { resolve } = require('@rollup/plugin-node-resolve')` doesn't work even in v8.1.0.

**Comment by shellscape** [comment]
> The issue is still not fixed. const { resolve } = require('@rollup/plugin-node-resolve') doesn't work even in v8.1.0.

@XhmikosR the code cited doesn't exist in the readme at present.

**Comment by XhmikosR** [comment]
True, but the way listed here seems to still work as a replacement for the old way of `require`ing packages.

**Comment by heavyk** [comment]
@vladshcherbin with the latest 8.1.0, it still exports an object instead of a function:

```
> require('@rollup/plugin-node-resolve')
{
  DEFAULTS: {
    customResolveOptions: {},
    dedupe: [],
    extensions: [ '.mjs', '.js', '.json', '.node' ],
    resolveOnly: []
  },
  default: [Function: nodeResolve],
  nodeResolve: [Function: nodeResolve]
}
> require('@rollup/plugin-commonjs')
[Function: commonjs]
```

**Comment by shellscape** [comment]
Thanks for weighing in everyone.

**Pull request merged**
