### PR TITLE
fix(commonjs): convert module.exports with `__esModule` property(#939)

### PR DESCRIPTION
**Pull request by githoniel**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [X] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [X] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [X] no

List any relevant issue numbers: #939 

### Description

transform commonjs  as `module.exports = { __esModule: true, default: ... }` to wrap runtime code

### CODE REVIEW

**Comment by guybedford** [comment]
@githoniel as well as the unit test here, could you include a full end-to-end test of the original use case provided in https://github.com/rollup/plugins/issues/939?

It looks like the output of that test is currently:

```
{ default: 'symbol', __esModule };
'symbol2'
```

Can you clarify what the output of that same test becomes with this PR?

**Comment by githoniel** [comment]
@guybedford thank for your time. 

Look at this https://replit.com/@githoniel/rollup-plugin-repro-1

many old package output code like below

```
module.exports = { 
  "default": () => { console.log('beep') },
   __esModule: true 
};
```

they are not supported by current commojs plugin

**Comment by guybedford** [comment]
One issue here is this is the opposite interop pattern to Node.js itself... making this plugin unsuitable for building Node.js applications.

**Comment by githoniel** [comment]
any idea？shall we add options like `target: 'browse' | 'node'`

**Comment by guybedford** [comment]
@githoniel I believe this is supposed to be controled by the `defaultIsModuleExports` configuration option - https://github.com/rollup/plugins/tree/master/packages/commonjs#defaultismoduleexports. So this PR should be sure to follow the semantics of that option as well I think.

**Comment by githoniel** [comment]
> @githoniel I believe this is supposed to be controled by the `defaultIsModuleExports` configuration option - https://github.com/rollup/plugins/tree/master/packages/commonjs#defaultismoduleexports. So this PR should be sure to follow the semantics of that option as well I think.

I have make it work and update new tests

**Review by guybedford — APPROVED** [review]
Great work checking these cases, thanks for the PR.

**Comment by guybedford** [comment]
I know the prettier issue is unrelated, but are you able to get the CI to pass on this PR?

**Comment by guybedford** [comment]
Finally passing - thanks again for your work on this.

**Pull request merged**
