### PR TITLE
fix(plugin-inject): isReference check bug

### PR DESCRIPTION
**Pull request by linsk1998**
plugin-inject. isReference disregard ImportSpecifier

## Rollup Plugin Name: `plugin-inject`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

disregard the `bar` in `import { bar as foo }`

### CODE REVIEW

**Comment by lukastaegert** [comment]
Maybe it would make more sense to replace the logic with https://github.com/Rich-Harris/is-reference? This is what other plugins use so there is only one place that needs to be kept up to date with new language features. Plugins that reimplement the logic are usually older. Any thoughts @shellscape ?

**Comment by shellscape** [comment]
Thanks for this PR. Definitely agree.

**Comment by shellscape** [comment]
@linsk1998 curious turn of events there. can you let us know why you closed it?

**Comment by linsk1998** [comment]
@shellscape  I commit tests. And then Circleci Task throw a timeout error. It's Circleci problem not code. But I can not pull request. So I create new PR

**Pull request closed without merging**
