### PR TITLE
Expose the virtual `require` function on mock `module` (Closes #307)

### LINKED ISSUE #307: `@rollup/plugin-commonjs`: Can't export `require` function
- Rollup Plugin Name: 
@rollup/plugin-commonjs
- Rollup Plugin Version: 11.1.0
- Rollup Version: 2.6.1
- Operating System (or Browser): windows
- Node Version: 12

### How Do We Reproduce?

Not sure, found here https://github.com/fisker/serve-directory/pull/987/files#diff-8bd3313bc91cf9200da0f98030dfc948R14 , workaround use `global.require`

### Expected Behavior

Should works

### Actual Behavior

```text
src/core/imports.js: (14:17)
[!] Error: Unexpected token
src/core/imports.js (14:17)
12:   pkg: package_,
13:   require,
14:   ...utils,
               ^
15: })
Error: Unexpected token
```

### PR DESCRIPTION
**Pull request by danielgindi**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [ ] yes (_bugfixes and features will not be merged without tests_)
- [x] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

List any relevant issue numbers: #307

### Description

This simply exposes the virtual `require` function in the virtual `module` object's properties.  
It's the best we can do, I think, to support those extreme use cases.

### CODE REVIEW

**Comment by lukastaegert** [comment]
It looks sensible but I would feel better if we had a test that uses this, at the very least for documentation purposes, but also to see if this works as intended.

**Comment by danielgindi** [comment]
@lukastaegert Well it looked sensible but was not complete ;-) Now it is. If someone counted on `module.require` to have consistent behavior with `require` it would not work as `createCommonjsModule` did not export `require` (cases without dynamic requires).

Now it does. It "spams" the snapshots a bit because it makes `commonjsRequire` stick around in some cases where it was being tree-shaken off before.  
Now this is something that bothered me a bit, and I played with the idea of making the transformer replace `typeof module.require` with `typeof commonjsRequire` in the exact same way it does for `typeof require`. This would allow us to omit `require` member of `module`, and keep the code cleaner in some cases, but will destroy the semantic of `module.require` (if it matters).

What do you say?

**Comment by danielgindi** [comment]
As it turns out, I had to combine both idea to make it fully work. As in some cases (`module.require` inside a `createCommonjsModule` call) - the `module` is in scope, not global anymore, so we're not modifying it.
Now we're both replacing global `module.require` expressions/calls with `commonjsRequire`, and exposing `require` on the fake `module`s so they are available for the more extreme cases.

**Comment by lukastaegert** [comment]
I was wondering if we could have a functional test that actually shows that this function is able to require something and especially that it uses the correct parent module to resolve imports.

**Comment by danielgindi** [comment]
@lukastaegert 
Well right now its bypassing the direct call to `module.require` because I had some issues with it (specifically keeping the context).
My back kills me, I'll work on this a bit more tomorrow night, try to have a solution I'm satisfied with. 
We will probably need to keep the fake local path in the module's object to have context, and wrap its `require` member to call the dynamic require function with said context.

**Comment by danielgindi** [comment]
@lukastaegert Okay I did manage to do that, we keep the context, and the `dynamic-module-require` test is testing it end-to-end.

**Pull request merged**
