### PR TITLE
fix(esm-shim): do not insert shims at `import` literal

### LINKED ISSUE #1649: [@rollup/plugin-esm-shim] Import regex fails if the the code contains an "import" string followed by more content
- Rollup Plugin Name: @rollup/plugin-esm-shim
- Rollup Plugin Version: 0.1.5
- Rollup Version: 4.8.0
- Operating System (or Browser): Mac
- Node Version: v21.2.0
- Link to reproduction: live https://stackblitz.com/edit/rollup-repro-pba1zx?file=dist%2Fmain.js
or as zip [rollup-repro-pba1zx.zip](https://github.com/rollup/plugins/files/14127398/rollup-repro-pba1zx.zip)

### Expected Behavior

The shim to be inserted in the right place with a simple config:

```js
const resolve = require('@rollup/plugin-node-resolve');
const commonjs = require('@rollup/plugin-commonjs');
const esmShim = require('@rollup/plugin-esm-shim');

module.exports = {
  input: 'src/main.js',
  output: {
    file: 'dist/main.js',
    format: 'es',
  },
  plugins: [resolve(), commonjs(), esmShim()],
};
```

from a simple source:

```js
const dn = __dirname;

module.exports = {
  keyword: ' import',
  dn: '',
};
```

### Actual Behavior

The shims get inserted in the middle of the common js helper.

```js
function getDefa
// -- Shims --
import cjsUrl from 'node:url';
import cjsPath from 'node:path';
import cjsModule from 'node:module';
const __filename = cjsUrl.fileURLToPath(import.meta.url);
const __dirname = cjsPath.dirname(__filename);
const require = cjsModule.createRequire(import.meta.url);
ultExportFromCjs (x) {
	return x && x.__esModule && Object.prototype.hasOwnProperty.call(x, 'default') ? x['default'] : x;
}

__dirname;

var main = {
  keyword: ' import',
  dn: '',
};

var main$1 = /*@__PURE__*/getDefaultExportFromCjs(main);

export { main$1 as default };
```

### Additional Information

- The issue happens with or without any real esm/require "import"s at the top of the file.
- The issue seems to only happens if there is a space before the import string and if there's more "content" in the file after that import string
- The behavior can be reproduced without rollup (using ESMStaticImportRegex and MagicString from utils provideCJSSyntax)
- The above is a reduced test case that comes from a real world usage of highlight.js qml language (see source with import string here https://github.com/highlightjs/highlight.js/blob/6317acd780bfe448f75393ea42d53c0149013274/src/languages/qml.js#L17)

### PR DESCRIPTION
**Pull request by GODLiangCY**
## Rollup Plugin Name: `@rollup/plugin-esm-shim`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

resolves #1649 

### Description

See the repro #1649 given, the shims were inserted into wrong position because the object
```js
{
  keyword: ' import',
  dn: '',
};
```
matches the `ESMStaticImportRegex` regex.

This PR fixes it by disallowing `\n` in the specifier group in the regex.

### CODE REVIEW

**Comment by tada5hi** [comment]
looking good

**Review by tada5hi — APPROVED** [review]

**Comment by GODLiangCY** [comment]
ping politely here. can anyone help merge this pr

**Review by lukastaegert — APPROVED** [review]
Looks good to me.

**Comment by georg-schwarz** [comment]
Is this change already published as a new release? Because I'm getting an error in `v0.1.6`:

```
Expected ":" but found "import"
[...]
2  |  // -- Shims --
3  |  import cjsUrl from 'node:url';
   |  ^
4  |  import cjsPath from 'node:path';
5  |  import cjsModule from 'node:module';
```

**Pull request merged**
