### PR TITLE
fix(replace): add missing types for new `preventAssignment` option

### LINKED ISSUE #812: @rollup/plugin-replace failing since 2.4.0
- Rollup Plugin Name: @rollup/plugin-replace
- Rollup Plugin Version: 2.4.0
- Rollup Version: 2.39.0
- Operating System (or Browser): Windows & Linux
- Node Version: 14
- Link to reproduction _(⚠️ read below)_: https://github.com/mendix/widgets-resources/pull/469/checks?check_run_id=1952183540

### Expected Behavior
Pass builds without throw error

### Actual Behavior
Throwing the following error: Error: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to true, as the next major version will default this option to true.

Even adding preventAssignment it throws the error and rollup aborts the builds.

### Additional Information
It is happening since the last update 12h ago

### PR DESCRIPTION
**Pull request by danielroe**
## Rollup Plugin Name: `@rollup/replace`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:

### Description

🤦‍♂️ Failed to add types for change in previous PR (#798). Closes #812.

### CODE REVIEW

**Comment by diego-antonelli** [comment]
@danielroe I am pretty dure my error is not related to typings, as I am not executing it in typescript.

**Comment by danielroe** [comment]
@diego-antonelli Would you check - I noticed your tests are written in TypeScript?

**Comment by diego-antonelli** [comment]
> @diego-antonelli Would you check - as I noticed your tests are written in TypeScript? (A type error would cause jest specs to fail, whereas the warning _shouldn't_ cause rollup to abort the build - but I might be wrong!)

I am doing a quick test, please wait 5 min to merge this PR, please

**Comment by diego-antonelli** [comment]
@danielroe indeed was just the typings. Funny thing is: Jest is simply dying without throw any error, but this is not related to your fix. Thanks a lot for the quick fix!!

**Comment by shellscape** [comment]
Thanks for the PR. Looks like a few checks are failing there. Please have a look.

**Comment by danielroe** [comment]
@shellscape The unit tests are all succeeding. Looks like it is a `codecov` failure(?) -  not sure how to diagnose.

**Comment by shellscape** [comment]
okay thanks for taking a look. I'll see what I can do about that in a few hours today

**Review by shellscape — APPROVED** [review]

**Comment by shellscape** [comment]
Looks like codecov is having some issues today. We'll bypass. Thanks for the fix.

**Pull request merged**
