### PR TITLE
fix(commonjs): resolve export "exports" not found

### LINKED ISSUE #1306: [@rollup/plugin-commonjs] does not provide an export named 'exports'
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 22.0.2
- Rollup Version: 2.79.1
- Operating System (or Browser): Ubuntu, Chromium
- Node Version: v16.17.1
- Link to reproduction _(⚠️ read below)_: https://github.com/lucaelin/rollup-commonjs-bug

I recently took a deep dive into some issues related to the `@web/dev-server` in conjunction with the commonjs plugin. You can read up on those related issues [here](https://github.com/modernweb-dev/web/issues/1700#issuecomment-1264052647). One remaining issue is with this plugin and the above error message. The commonjs-plugin injects an import statement using this logic [here](https://github.com/rollup/plugins/blob/master/packages/commonjs/src/generate-imports.js#L111), but the generated output [here](https://github.com/rollup/plugins/blob/master/packages/commonjs/src/index.js#L257) does not provide the expected export-signature.

Apparently rollup itself does not show the same issue, which makes me wonder what I am missing in my analysis and if this is actually a bug in this plugin or if the `@web/dev-server` is actually at fault here. Any input is greatly appreciated! 

### Expected Behavior
web-dev-server should be able to transpile individual modules and pass module and import resolution over to the browser

### Actual Behavior
The browser shows an error message, because the export signature of the `?commonjs-module` stub does not match the signature of the generated import. Namely an export named exports is missing. 

### Additional Information
see above

### PR DESCRIPTION
**Pull request by lukastaegert**
## Rollup Plugin Name: `commonjs`

This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] documentation
- [ ] other

Are tests included?

- [x] yes (_bugfixes and features will not be merged without tests_)
- [ ] no

Breaking Changes?

- [ ] yes (_breaking changes will not be merged unless absolutely necessary_)
- [x] no

If yes, then include "BREAKING CHANGES:" in the first commit message body, followed by a description of what is breaking. 

List any relevant issue numbers:
- resolves #1306 
- may resolve some of the issues listed in the thread of #986

### Description
Previously, this plugin relied on "synthetic named exports" to get a reference for the `module.exports` export of a module in a way that would update if `module.exports` is reassigned.
This apparently caused issues, so this PR changes that to instead use a getter and setter that updates `exports` if `module.exports` is reassigned.

### CODE REVIEW

**Review by shellscape — APPROVED** [review]
Feel free to merge 🎉

**Comment by lukastaegert** [comment]
Currently thinking about this, maybe I know a solution that is even more CommonJS spec compliant, let me check. Will convert it to draft for a moment.

**Comment by lukastaegert** [comment]
Turns out my other idea did not really work out. As I already got the go for this, I will merge this one now.

**Comment by wizardist** [comment]
@lukastaegert would you consider merging a patch to replace `get`/`set` with `Object.defineProperty()`? It would help building for some ES3 runtimes, incl. older Rhino builds. Or is it an absolute no go?

**Comment by lukastaegert** [comment]
The code in question is theoretically included for every single CommonJS module. Using `Object.defineProperty` can blow the code up quite a bit and potentially harm tree-shaking for everyone. Can't you run a code transform plugin to rewrite the accessors?

**Comment by wizardist** [comment]
Yes, that’s our coping strategy for the time being. Thanks!

**Pull request merged**
